# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75e6e6d126eec9ab6b120bf7f1e8358c60d032a16f05dc7a93df5f7cd089cc753d414c358d7ee010bc914e9a4ad4e4cf54b344f7deb69bdc3dc401827244436b

test:
  secret_key_base: 963987674ab8fd5925639e0606a2d5a54ca1fd3e09be97a770ab6b27d490263d16fceeeb6dc893220236e21b60e9b2cb368392d47e4c310109ad3a6cd628ed16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
